# R code to visualize cluster system data from R
# Few R packages are expected to have been installed (ggplot2 mainly)
# options.r contains run specific global variables for R (generated by callee script)

source("options.r")
source("multiplot.r")
library(ggplot2)
library(plyr)
#library(lattice)
#library(doSNOW)
#library(foreach)
#library(car)


# breaks is a vector that includes bin values
# return % of sample that reside in each bin values
GetPercentageinBin <- function(data,breaks) {
  h = hist(data,breaks,plot=FALSE)
  return (h$counts*100/sum(h$counts))
}

GetOptimalBreaks <- function(clusterdata.list,data.colname,separator) {
  if (breaks.log == FALSE) {
    minval = min(clusterdata.list[data.colname])
   maxval = max(clusterdata.list[data.colname])
   if (maxval <= 0)
      return (NA)
    bin.size = 16
    if (maxval > 10000) # Hack to allow big #s to be printed
      bin.size=10
    breaks = seq(0,maxval,maxval/bin.size)
    return (breaks)
  } else {
    minval = min(clusterdata.list[data.colname])
    maxval = max(clusterdata.list[data.colname])
    if (maxval <= 0)
      return (NA)
    bin.size = 16
    newlogbins = seq(0, bin.size)
    logbreaks = 2^newlogbins
    logbreaks[[1]] = 0
    if (maxval > logbreaks[[17]])
      logbreaks[[17]] = maxval
    return (logbreaks)
  }
}


# return a data frame that contains the matrix of histogram data across hosts
# [node bin.tag bin.val value] Example,

GetClusterBarplotData <- function(clusterdata.list,data.colname,separator) {
  breaks = GetOptimalBreaks(clusterdata.list,data.colname,separator)
  if (is.na(breaks[1]) == TRUE)
    return (NULL)
  nbins = length(breaks)-1
  nrows = nbins*nnodes
  df <- data.frame(row.names = paste("row.",c(1:nrows),sep=""))
  df[,"node"] <- sort(rep(node.name,nbins))
  df[,"bin.tag"] = rep(paste("Bin ",c(1:nbins),sep=""),nnodes)
  df[,"bin.val"] = round(rep(breaks[2:length(breaks)],nnodes),max.decimals)

  node.val = c()
  for (i in 1:nnodes) {
    host = node.name[i]
    host_upper = toupper(node.name[i])
    node.dataall = subset(clusterdata.list, eval(parse(text=separator)) == host 
                          | eval(parse(text=separator))  == host_upper)
    node.data = as.numeric(unlist(node.dataall[data.colname]))
    data.perc = GetPercentageinBin(node.data,breaks)
    node.val = c(node.val,data.perc)
  }
  df[,"value"] = as.vector(node.val)

  return (df)
}

